export enum CovenantBankslipSegmentEnum {
  CITY_HALL = 1,
  SANITATION = 2,
  GAS_AND_ELECTRIC_ENERGY = 3,
  TELECOMUNICATION = 4,
  GOVERNMENT_AGENCIES = 5,
  MEAT_AND_SIMILAR_OR_DOCUMENT_NUMBER_ID_COMPANIES = 6,
  TRAFFIC_TICKETS = 7,
  BANK_EXCLUSIVE_USE = 9
}
